

name: Continuous Integration

on:
  push:
    branches:
      - [cite_start]"test/v1.0.0" # Triggers the workflow on push to the test branch [cite: 60]
  pull_request:
    branches:
      - [cite_start]"prod/v1.0.0" # Triggers the workflow on pull requests to the prod branch [cite: 61]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22" 
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install 

      - name: Build projects
        run: pnpm run build 
  